[[plugins]]
# https://github.com/subnut/visualstar.vim
repo = 'thinca/vim-visualstar'


[[plugins]]
# https://github.com/tyru/open-browser.vim
repo = 'tyru/open-browser.vim'
lua_add = '''
vim.g.netrw_nogx = 1  -- disable netrw's gx mapping.
vim.api.nvim_set_keymap('n', 'gx', '<Plug>(openbrowser-smart-search)', { noremap = false, silent = true })
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
lua_add = '''
require("plugins/glyph-palette")
'''

[[plugins]]
repo = 'vimtry1/today.vim'

[[plugins]]
# https://github.com/monaqa/dial.nvim
repo = 'monaqa/dial.nvim'
lua_add = '''
require("plugins/dial")
'''

[[plugins]]
# https://github.com/kylechui/nvim-surround
repo = 'kylechui/nvim-surround'
lua_add = '''
require("nvim-surround").setup({})
'''

[[plugins]]
# https://github.com/MattesGroeger/vim-bookmarks
repo = 'MattesGroeger/vim-bookmarks'

[[plugins]]
# https://github.com/hrsh7th/nvim-cmp
repo = 'hrsh7th/nvim-cmp'

[[plugins]]
# https://github.com/karb94/neoscroll.nvim
repo = 'karb94/neoscroll.nvim'
lua_add = '''
require('neoscroll').setup()
'''
[[plugins]]
# https://github.com/Equilibris/nx.nvim
repo = 'Equilibris/nx.nvim'
lua_add = '''
require("plugins/nx")
'''

[[plugins]]
# https://github.com/jackMort/ChatGPT.nvim 
repo = 'jackMort/ChatGPT.nvim'
depends = ['MunifTanjim/nui.nvim', 'nvim-lua/plenary.nvim', 'nvim-telescope/telescope.nvim']
lua_add = '''
require("plugins/ChatGPT")
'''

[[plugins]]
# https://github.com/preservim/nerdcommenter
repo = 'preservim/nerdcommenter'
lua_add = 'require("plugins/nerdcommenter")'

[[plugins]]
# https://github.com/folke/zen-mode.nvim
repo = 'folke/zen-mode.nvim'
lua_add = '''
vim.keymap.set("n", "<C-z>", ":ZenMode<CR>")
'''

[[plugins]]
repo = 'kevinhwang91/promise-async'

[[plugins]]
# https://github.com/kevinhwang91/nvim-ufo
repo = 'kevinhwang91/nvim-ufo'
depends = ['kevinhwang91/promise-async']
lua_add = '''
require("plugins/nvim-ufo")
'''

