[[plugins]]
# https://github.com/ellisonleao/gruvbox.nvim
repo = 'ellisonleao/gruvbox.nvim'

[[plugins]]
# https://github.com/catppuccin/nvim
repo = 'catppuccin/nvim'

[[plugins]]
repo = 'sainnhe/everforest'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
# https://github.com/jacoborus/tender.vim
repo = 'jacoborus/tender.vim'
