[[plugins]]
repo = 'lambdalisue/fern.vim'
lua_add = 'require("plugins/fern")'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = ['lambdalisue/fern.vim']

[[plugins]]
repo = 'lambdalisue/fern-bookmark.vim'
lua_add = '''
vim.api.nvim_set_keymap('n', '<C-b>', ':Fern bookmark:///<CR>', { noremap = true, silent = true })
'''
depends = ['lambdalisue/fern.vim']

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
lua_add = '''
vim.g["fern#renderer"] = "nerdfont"
'''
