git:
  parseEmoji: true

gui:
  showIcons: true

customCommands:
  - key: "c"
    context: "files"
    description: "commit files with format"
    prompts:
      - type: "input"
        title: "Enter the Message"
        key: "Message"
        initialValue: ""
      - type: "menu"
        title: "Choise the emoji"
        key: "Emoji"
        options:
          - name: "(empty)"
            description: ""
            value: ""
          - name: ":ambulance:"
            description: "(fix)🚑致命的なバグ修正"
            value: ":ambulance:"
          - name: ":bug:"
            description: "(fix)🐛バグ修正"
            value: ":bug:"
          - name: ":+1:"
            description: "(fix)👍機能改善や機能修正"
            value: ":+1:"
          - name: ":cop:"
            description: "(fix)👮セキュリティ関連の修正"
            value: ":cop:"
          - name: ":tada"
            description: "(feat)🎉大きな機能追加"
            value: ":tada:"
          - name: ":sparkles:"
            description: "(feat)✨部分的な機能追加"
            value: ":sparkles:"
          - name: ":up:"
            description: "(feat)🆙依存パッケージ等のアップデート"
            value: ":up:"
          - name: ":memo:"
            description: "(docs)📝ドキュメントの追加や修正"
            value: ":memo:"
          - name: ":bulb"
            description: "(docs)💡ソースコードへのコメント追加や修正"
            value: ":bulb:"
          - name: ":art:"
            description: "(style)🎨レイアウト関連の修正"
            value: ":art:"
          - name: ":lipstick:"
            description: "(style)💄Lintエラーの修正やコードスタイルの修正"
            value: ":lipstick:"
          - name: ":recycle:"
            description: "(refactor)♻️ リファクタリング"
            value: ":recycle:"
          - name: ":fire:"
            description: "(refactor)🔥コードやファイルの削除"
            value: ":fire:"
          - name: ":green_heart:"
            description: "(test)💚テストやCIの修正"
            value: ":green_heart:"
          - name: ":rocket:"
            description: "(perf)🚀パフォーマンス改善"
            value: ":rocket:"
          - name: ":wrench:"
            description: "(chore)🔧設定ファイルの修正"
            value: ":wrench:"
          - name: ":building_construction:"
            description: "(chore)🏗️アーキテクチャの修正"
            value: ":building_construction:"
          - name: ":construction:"
            description: "(wip)🚧作業中"
            value: ":construction:"
    command: 'bash -c ''message="{{.Form.Message}}"; emoji="{{.Form.Emoji}}"; commit_message="$emoji $message"; git commit -m "$commit_message"'''
    loadingText: "Commiting..."
